# Generated by Django 4.2.1 on 2023-05-05 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soout',
            options={'managed': True, 'verbose_name': 'SO Out'},
        ),
        migrations.AddField(
            model_name='shift',
            name='green_start',
            field=models.TimeField(blank=True, default=datetime.time(4, 45), null=True, verbose_name='Green Zone Start'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='red_start',
            field=models.TimeField(blank=True, default=datetime.time(5, 0), null=True, verbose_name='Red Zone Start'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='yellow_start',
            field=models.TimeField(blank=True, default=datetime.time(6, 15), null=True, verbose_name='Yellow Zone Start'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 5), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(blank=True, default='05:46', null=True, verbose_name='Time Arrived'),
        ),
    ]
