# Generated by Django 4.2.1 on 2023-05-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_soout_options_shift_green_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soout',
            name='co_time_arrived',
            field=models.TimeField(blank=True, default='05:47', null=True, verbose_name='Time Arrived'),
        ),
    ]
